### ISSUE TITLE
[Bug] When makes poll with Ping someone or channel, it will show ID

### ISSUE THREAD

**Issue by Stupid-Benz** [windowsboy111/merlin-py#18]
Please fix the bug

**Comment by windowsboy111** [comment]
pings for channels and members are visually `@windowsboy111` but it's actually `<@1234567>`, which `1234567` represents the id.
The title of an embed shows the ping as the original string, this is the limitation of discord, it is likely not going to be worked on.

**Comment by windowsboy111** [comment]
The way to go is to replace that with pure string `@windowsboy111#1024`.
