### ISSUE TITLE
[Suggestion] Make the Poll ID shorter

### ISSUE THREAD

**Issue by Stupid-Benz** [windowsboy111/merlin-py#8]
Make a new shorter Poll ID

**Comment by windowsboy111** [comment]
shall i make the poll id readable or can it be something like `&a9C*nM` and `p@&QNm7`

**Comment by Stupid-Benz** [comment]
I think need to do `mmddhhmm`, months, day, hour, minutes

**Comment by windowsboy111** [comment]
it is not a good idea.  
you see, if you use the date and time, you are using the time of the bot.  
and also, if you know there's a poll issued at a specific time, you can end it if you know the time, which is not a good idea.  
I does not suggest doing so.

**Comment by Stupid-Benz** [comment]
Okay then use a random numbers in five digit, no with `!@#$%^&*()`, hard to type in phone

**Comment by windowsboy111** [comment]
you can use the message id if you are using phone, i guess i can use both.

**Comment by Stupid-Benz** [comment]
sirius think msg id is not okay so use a new id

**Comment by windowsboy111** [comment]
we should allow backwards compatibility

**Comment by Stupid-Benz** [comment]
idk

**Comment by Stupid-Benz** [comment]
yes
i think allow backwards compatibility

**Comment by Stupid-Benz** [comment]
End this ??

**Comment by Stupid-Benz** [comment]
Although using base 64 become longer
but now make the code can end the poll by using decode

**Comment by windowsboy111** [comment]
we have to make a shorter one, Not a longer one, this is not what we are aiming for. This cannot be ended.

**Comment by Stupid-Benz** [comment]
So I used `hex()` make base 10 to base 16

**Comment by Stupid-Benz** [comment]
Now, I am going to make the code end-able

**Comment by Stupid-Benz** [comment]
Finished

**Comment by Stupid-Benz** [comment]
Am I going to Make a Pull request??

**Comment by windowsboy111** [comment]
Does it look shorter?

**Comment by Stupid-Benz** [comment]
ummm
ys
shorter

**Comment by Stupid-Benz** [comment]
from 18 ==> 15

**Comment by Stupid-Benz** [comment]
It can end-able now

**Comment by windowsboy111** [comment]
Should work now

**Comment by windowsboy111** [comment]
Since the id has shorten like 2 or 3 characters only, I am going to make it even shorter by converting it to base64.
