### ISSUE TITLE
[BUG/ISSUE] WARNING SYSTEM cannot use special characters

### ISSUE THREAD

**Issue by windowsboy111** [windowsboy111/merlin-py#9]
**Describe the bug**
using special characters might break the system

**To Reproduce**
1. /warn @someone test '\x1b?"\"\'
2. /ckwn
3. nothing happened despite deleted command issuing message

**Expected behavior**
it should work fine

**Screenshots**

**Comment by windowsboy111** [comment]
The issue has been temporarily fixed, and will be out in next beta version.
However, the warning system will be changed to be SQL powered. I am concerned about SQL injection and thinking a way to prevent it…

**Comment by Stupid-Benz** [comment]
okay
Are you going to use SQL??

**Comment by windowsboy111** [comment]
sure.

**Comment by windowsboy111** [comment]
originally there's a security issue in the sqlite3 library that can allow SQL injection. now it has been fixed.
It is still in testing period, it is still not fully working.

**Comment by windowsboy111** [comment]
This should be fixed in [the newest release](https://github.com/windowsboy111/merlin-py/releases/tag/2.1-b).  
Thx!
